# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='owner',
            field=models.CharField(default='stupid', max_length=200),
        ),
    ]
